
server:
  port: 8081

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/provider
    username: popos
    password: Cp1Kr!Mp
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

ureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
